### ISSUE TITLE
Relatório Danfe Nfe

### ISSUE THREAD

**Issue by rmalavazigalli** [Samuel-Oliveira/Java_Danfe#18]
Na linha 1928 do relatório da danfe da nfe
(src/main/resources/jasper/nfe/danfe.jrxml) 

tem um erro, poderia verificar?

`			</textField>
		</band>
	</pageFooter>
</jasperReport>
eFooter>
</jasperReport>`

**Comment by Samuel-Oliveira** [comment]
Corrigido, obrigado por notificar.
Nenhuma versao é necessaria, o Jasper combilado nao estava com o problema!
