### ISSUE TITLE
Conteudo do PDF saindo em Branco

### ISSUE THREAD

**Issue by eduardocerqueirasilva** [Samuel-Oliveira/Java_Danfe#2]
Boa tarde, estou tentando gerar o arquivo pdf da danfe, o mesmo faz a leitura do xml corretamente, salva na pasta corretamente, porem o conteúdo do pdf sai em branco, eu estou usando a lib que foi disponibilizada nesse link [https://github.com/Samuel-Oliveira/Java_Danfe/raw/master/java-danfe-1.0.jar](url)

**Comment by Samuel-Oliveira** [comment]
Resolvido versão 1.2
