### ISSUE TITLE
org.xml.sax.SAXParseException: The entity name must immediately follow the '&' in the entity reference.

### ISSUE THREAD

**Issue by lucianoapg** [Samuel-Oliveira/Java_Danfe#6]
O erro ocorre ao tentar imprimir uma danfe cujo xml possui caracter especial, por ex: '&'.

Efetuei uma correção do .jrxml e gostaria de submeter para sua análise.

**Comment by jonasricardo** [comment]
@lucianoapg estou com erro ao tentar gerar a DANFE por qualquer método da ImpressaoService, dado o erro de nullPointerException. 
Poderia enviar seu arquivo modificado para eu testar aqui se o problema foi solucionado?

Vi que você tem um fork da java_danfe em seus repositório, mas contem os mesmos arquivos jrxml

**Comment by lucianoapg** [comment]
Boa noite,
posso enviar sim,
Acabei de chegar de viagem, mas amanhã de manhã envio sem falta.


Atenciosamente.


Luciano
***@***.***)


Em sáb., 18 de fev. de 2023 às 20:13, jonasricardo ***@***.***>
escreveu:

**Comment by lucianoapg** [comment]
Boa noite,

segue o jrxml.


Atenciosamente.

Luciano
(MsN ***@***.***)


Em sáb., 18 de fev. de 2023 às 20:13, jonasricardo ***@***.***>
escreveu:

**Comment by lucianoapg** [comment]
Boa noite,
subi as alterações que fiz para prevenir o nullPointerException.


https://github.com/lucianoapg/Java_Danfe


Luciano
(MsN ***@***.***)


Em sáb., 18 de fev. de 2023 às 20:13, jonasricardo ***@***.***>
escreveu:
